### ISSUE TITLE
오류부분

### ISSUE THREAD

**Issue by minjeong12** [BonhaengLee/Capstone-base-project#13]
- [x] 로그인 하지 않았을 때 빈 화면이 뜸 

나머지는 찾으면 업데이트 하겠습니다!

**Comment by minjeong12** [comment]
- [ ]부엉이 만남 후기 작성했을 때 하나의 후기만 마이페이지에 뜸

**Comment by minjeong12** [comment]
- [ ] 회원가입 안 했을 때 nav 바에 searchbar 기능을 못한다. (삭제해도 될것 같아요)

**Comment by BonhaengLee** [comment]
> * [x]  로그인 하지 않았을 때 빈 화면이 뜸
> 
> 나머지는 찾으면 업데이트 하겠습니다!

cloud firestore rules 업데이트 후 해결
![Uploading image.png…]()

**Comment by BonhaengLee** [comment]
> * [x]  회원가입 안 했을 때 nav 바에 searchbar 기능을 못한다. (삭제해도 될것 같아요)

cloud firestore rules 업데이트 후 해결
![image](https://user-images.githubusercontent.com/59217352/102324163-c4a1a580-3fc4-11eb-954b-921726e64384.png)

**Comment by BonhaengLee** [comment]
> * [x]   부엉이 만남 후기 작성했을 때 하나의 후기만 마이페이지에 뜸

**cloud firestore rules**
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read;
      allow write: if false;
    }
  }
}

**=>>** 

service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read;
      allow write;
    }
  }
}
적용 후 리뷰 작성되고 2개 출력됨
