### ISSUE TITLE
#1 재능교환-구인글 등록 시나리오 프로토타입 구현

### ISSUE THREAD

**Issue by BonhaengLee** [BonhaengLee/Capstone-base-project#3]
[설계실 요정 프로젝트 우선순위 1]
재능교환-구인글 등록 시나리오에 대한 프로토타입 구현

(1)
Feat. 구인글 작성 페이지 구현

2020.10.10 20:20
데이터를 입력 받고 부모 컴포넌트에서 출력됨을 확인

**Comment by BonhaengLee** [comment]
Feat. 네비게이션 바 라우팅 구현

2020.10.10 20:13 
네비게이션 바 라우팅 구현됨
재능교환 메인 페이지 => 구인글 작성 페이지 이동하는 라우팅 구현 예정 
![image](https://user-images.githubusercontent.com/59217352/95653677-5ad4cd80-0b35-11eb-9099-a8cc1818fecf.png)

**Comment by sysh0107** [comment]
글 쓴 데이터 필터에 맞게 분류하기
- list.js 파일에 각 데이터 샘플 만들기(JSON 형식)
- 필터에서 checkedItems로 선택된 목록과 데이터를 연결?? 이 필요하다.

**Comment by BonhaengLee** [comment]
dgsf

**Comment by BonhaengLee** [comment]
gyhdhgdhgfuyj

**Comment by BonhaengLee** [comment]
(2)
Feat. 샘플데이터 필터링 기능 구현

2020.10.10 20:13
샘플데이터를 필터링하여 출력하는 기능 구현
초기 전체 목록 구현 필요, 테이블 구성 수정 필요, DB연동 필요
재능교환 메인 페이지 => 구인글 작성 페이지 이동하는 라우팅 구현 예정

**Comment by BonhaengLee** [comment]
(4)
Feat. 한글매핑, 초기 목록 출력 구현

2020.10.16 12:56   
한글매핑, 초기 목록 출력 구현,
테이블 구성 수정 필요, DB연동 필요
재능교환 메인 페이지 => 구인글 작성 페이지 이동하는 라우팅 구현 예정

**Comment by BonhaengLee** [comment]
(5)
Style. 와이어프레임에 맞춰  CSS 일부 수정함.

2020.10.17 12:10
- 현재는 입력 받은 체크박스의 값을 하나라도 포함하는 모든 데이터가 출력되고 있으나, 
카테고리별 입력 받은 체크박스 값을 모두 포함하고 있는 데이터로 출력시켜주도록 구현할 예정
- DB연동 필요
-재능교환 메인 페이지 => 구인글 작성 페이지 이동하는 라우팅 구현 예정

**Comment by BonhaengLee** [comment]
(5)
Feat. 카테고리별 체크박스 값을 모두 포함하는 데이터가 출력되도록 필터링 구현

2020.10.17 12:10
- 검색어 필터링 기능 구현 필요
- 재능교환 메인 페이지 => 구인글 작성 페이지 이동하는 라우팅 구현 필요
- 구인글 목록 페이지 이동 기능 필요
- DB연동 필요

ex. 돈 + 부산
![image](https://user-images.githubusercontent.com/59217352/96328184-17b9b380-107b-11eb-8c6f-48c532717606.png)

ex. 돈 + 세종
![image](https://user-images.githubusercontent.com/59217352/96328196-3455eb80-107b-11eb-89ee-f13e2d9a00ce.png)

**Comment by BonhaengLee** [comment]
(7)
Feat. 검색어 필터링(진행중)

2020.10.19 15:32

- 검색어를 버튼으로 submit하면 필터하도록 개선 필요, 현재는 입력하면 체크박스의 값에 따라 바로 필터링됨
- 재능교환 메인 페이지 => 구인글 작성 페이지 이동하는 라우팅 구현 필요
- 구인글 목록 페이지 기능 필요
- DB연동 필요

![image](https://user-images.githubusercontent.com/59217352/96409706-a87dc400-1220-11eb-809f-23c2a614d1ec.png)

**Comment by BonhaengLee** [comment]
(8)
Feat. 검색어 필터링 개선

2020.10.19 18:50
검색 버튼을 누른 다음 필터링되도록 변경, 체크박스와 별개로 검색어 필터링 동작되도록 개선

-재능교환 메인 페이지 => 구인글 작성 페이지 이동하는 라우팅 구현 필요
-구인글 목록 페이지 기능 필요
-DB연동 필요

[체크박스]
![image](https://user-images.githubusercontent.com/59217352/96430742-83e41500-123d-11eb-82e3-2fb1ec9cf18e.png)

[검색어+체크박스]
![image](https://user-images.githubusercontent.com/59217352/96430786-91010400-123d-11eb-8154-51586749c233.png)

[검색어]
![image](https://user-images.githubusercontent.com/59217352/96430836-a24a1080-123d-11eb-951c-547af7341777.png)

[모든 입력 제거]
![image](https://user-images.githubusercontent.com/59217352/96430918-c148a280-123d-11eb-87b0-d1e0a2d4e1cb.png)
